[project]
name = "lightspeed-agent-eval"
version = "0.1.0"
description = "Agent evaluation package for lightspeed-core systems"
authors = []
requires-python = ">=3.11.1,<=3.12.9"
readme = "README.md"
license = {text = "Apache"}

dependencies = [
    "pandas>=2.1.4",
    "httpx==0.27.2",
    "tqdm>=4.67.1",
    "pyyaml>=6.0",
    "litellm>=1.0.0",
]

[project.optional-dependencies]
dev = [
    "black>=25.1.0",
    "mypy>=1.15.0",
    "ruff>=0.8.0",
    "pyright>=1.1.401",
    "pydocstyle>=6.3.0",
    "pylint>=3.3.2",
    "pytest>=8.3.2",
    "pytest-cov>=5.0.0",
]

[project.scripts]
agent-eval = "agent_eval.agent_eval:main"

[project.urls]
"Homepage" = "https://github.com/lightspeed-core/lightspeed-evaluation"
"Bug Tracker" = "https://github.com/lightspeed-core/lightspeed-evaluation/issues"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.ruff]
# always generate Python 3.11-compatible code.
target-version = "py311"
line-length = 100

[tool.ruff.lint.pydocstyle]
convention = "google" 